### ISSUE TITLE
Execution

### ISSUE THREAD

**Issue by imSunnyk** [aegilops/find_motion#1]
How can I run this python project?

**Comment by aegilops** [comment]
Use Python 3, clone the repo, then either run it from there or install it and run the command line script.

1. Clone the repo: `git clone https://github.com/aegilops/find_motion.git`
2. Change directory to the repo: `cd find_motion`

You can then either install it as a module, or run it directly.

# Install as a module
1. Install the module: `python3 -mpip install . --user`
2. Run the script: `find_motion`

# Run directly as a script
1. Install the dependencies manually: `python3 -mpip install -r requirements.txt --user`
2. Run the script directly: `./find_motion.py` or `python3 find_motion.py`
